site_name: OBO Relation Ontology
theme: readthedocs
nav:
  - home: index.md
  - usage:
      - guide: ROGuide.md
      - Annotation Properties: annotation-properties.md
      - Object Properties: ObjectProperty.md
      - Property Chains: PropertyChain.md
      - identifiers: Identifiers.md
      - shortcuts: ShortcutRelations.md
      - examples: UsageExamples.md
      - domainrange: domain-or-range-specific-relation.md
  - design patterns:
    - interaction: InteractionRelations.md
  - modules:
    - modules overview: ROModules.md
    - core: ROCore.md
    - neuron: RONeuro.md
    - causal: causal-relations.md
  - mappings:
    - sio: SioRoBridge.md
  - semantics:
    - bfo: ROAndBFO.md
    - time: ROAndTime.md
    - tqcs: TemporallyQualifiedContinuants.md
  - legacy:
    - oldro: DifferencesWithOldRO.md
    - chado: Using-RO-in-Chado.md
    - oboformat: OBOFormatUsersGuide.md
    - extract: ExtractingRelationsAsOboFormat.md
  - contributing:
    - editing: EditingRO.md
