name: Merge template

on:
  push:
    branches: [ master ]
    paths:
      - 'src/templates/new_relations.tsv'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/templates/new_relations.tsv'
  workflow_dispatch:

jobs:
  merge_template:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.3.0
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Reset ro-edit.owl
        run: |
          curl https://raw.githubusercontent.com/oborel/obo-relations/master/src/ontology/ro-edit.owl > src/ontology/ro-edit.owl
      - name: Run merge templates
        run: cd src/ontology && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' merge_template
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Merge template to ro-edit
          title: 'Merge template to ro-edit'
          body: |
            Merges the contents of src/templates/new_relations.tsv to ro-edit
          assignees: matentzn
